name: Factiii Production

# Application deployment workflow for production environment
# Handles testing, building, migrations with backup/restore, and rollback

on:
  pull_request:
    branches: [production, main]
  push:
    branches: [production, main]

jobs:
  test-and-build-pr:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.push.outputs.image_tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Read versions from config
        id: read-versions
        run: |
          if [ -f "factiiiAuto.yml" ]; then
            echo "âœ… factiiiAuto.yml found"
            sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
            sudo chmod +x /usr/local/bin/yq
            NODE_VERSION=$(yq eval '.node_version // "20"' factiiiAuto.yml)
            PNPM_VERSION=$(yq eval '.pnpm_version // "8"' factiiiAuto.yml)
            echo "ðŸ“¦ Detected Node version: $NODE_VERSION"
            echo "ðŸ“¦ Detected pnpm version: $PNPM_VERSION"
          else
            echo "âš ï¸  factiiiAuto.yml not found, using defaults"
            NODE_VERSION="20"
            PNPM_VERSION="8"
          fi
          echo "node_version=$NODE_VERSION" >> $GITHUB_OUTPUT
          echo "pnpm_version=$PNPM_VERSION" >> $GITHUB_OUTPUT

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ steps.read-versions.outputs.pnpm_version }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ steps.read-versions.outputs.node_version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --ignore-scripts || echo "âš ï¸ Install failed, continuing with Docker build"
        continue-on-error: true

      - name: Run tests
        run: pnpm run test:server || echo "âš ï¸ Tests skipped"
        continue-on-error: true

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Read config for Dockerfile path
        id: read-config
        run: |
          sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq
          
          if [ -f "factiii.yml" ]; then
            DOCKERFILE=$(yq eval '.dockerfile // "Dockerfile"' factiii.yml)
            REPO_NAME=$(yq eval '.name' factiii.yml)
            echo "dockerfile=$DOCKERFILE" >> $GITHUB_OUTPUT
            echo "repo_name=$REPO_NAME" >> $GITHUB_OUTPUT
          else
            echo "dockerfile=Dockerfile" >> $GITHUB_OUTPUT
            echo "repo_name=${{ github.event.repository.name }}" >> $GITHUB_OUTPUT
          fi

      - name: Build and push Docker image to ECR
        id: push
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY || 'apps' }}
          REPO_NAME: ${{ steps.read-config.outputs.repo_name }}
          DOCKERFILE: ${{ steps.read-config.outputs.dockerfile }}
        run: |
          echo "ðŸ”¨ Building Docker image from $DOCKERFILE..."
          docker build --platform linux/amd64 -f $DOCKERFILE -t $ECR_REGISTRY/$ECR_REPOSITORY:${REPO_NAME}-prod .
          
          echo "ðŸ“¤ Pushing to ECR..."
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:${REPO_NAME}-prod
          
          echo "image_tag=${REPO_NAME}-prod" >> $GITHUB_OUTPUT
          echo "âœ… Image built and pushed: $ECR_REGISTRY/$ECR_REPOSITORY:${REPO_NAME}-prod"
          echo "ðŸ’¡ To deploy to production, run: npx factiii deploy production"

  build-and-push-production:
    if: github.event_name == 'push' && (github.ref == 'refs/heads/production' || github.ref == 'refs/heads/main')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Read versions from config
        id: read-versions
        run: |
          if [ -f "factiiiAuto.yml" ]; then
            echo "âœ… factiiiAuto.yml found"
            sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
            sudo chmod +x /usr/local/bin/yq
            NODE_VERSION=$(yq eval '.node_version // "20"' factiiiAuto.yml)
            PNPM_VERSION=$(yq eval '.pnpm_version // "8"' factiiiAuto.yml)
            echo "ðŸ“¦ Detected Node version: $NODE_VERSION"
            echo "ðŸ“¦ Detected pnpm version: $PNPM_VERSION"
          else
            echo "âš ï¸  factiiiAuto.yml not found, using defaults"
            NODE_VERSION="20"
            PNPM_VERSION="8"
          fi
          echo "node_version=$NODE_VERSION" >> $GITHUB_OUTPUT
          echo "pnpm_version=$PNPM_VERSION" >> $GITHUB_OUTPUT

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ steps.read-versions.outputs.pnpm_version }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ steps.read-versions.outputs.node_version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --ignore-scripts || echo "âš ï¸ Install failed, continuing with tests"
        continue-on-error: true

      - name: Run tests
        run: pnpm run test:server || echo "âš ï¸ Tests skipped"
        continue-on-error: true

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Read config for Dockerfile path
        id: read-config
        run: |
          sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq
          
          if [ -f "factiii.yml" ]; then
            DOCKERFILE=$(yq eval '.dockerfile // "Dockerfile"' factiii.yml)
            REPO_NAME=$(yq eval '.name' factiii.yml)
            echo "dockerfile=$DOCKERFILE" >> $GITHUB_OUTPUT
            echo "repo_name=$REPO_NAME" >> $GITHUB_OUTPUT
          else
            echo "dockerfile=Dockerfile" >> $GITHUB_OUTPUT
            echo "repo_name=${{ github.event.repository.name }}" >> $GITHUB_OUTPUT
          fi

      - name: Build and push Docker image to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY || 'apps' }}
          REPO_NAME: ${{ steps.read-config.outputs.repo_name }}
          DOCKERFILE: ${{ steps.read-config.outputs.dockerfile }}
        run: |
          echo "ðŸ”¨ Building Docker image from $DOCKERFILE..."
          docker build --platform linux/amd64 -f $DOCKERFILE -t $ECR_REGISTRY/$ECR_REPOSITORY:${REPO_NAME}-prod .
          
          echo "ðŸ“¤ Pushing to ECR..."
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:${REPO_NAME}-prod
          
          echo "âœ… Image built and pushed: $ECR_REGISTRY/$ECR_REPOSITORY:${REPO_NAME}-prod"
          echo "ðŸ’¡ To deploy to production, run: npx factiii deploy production"
