name: Factiii Deploy

# Manual deployment workflow triggered by npx factiii deploy command
# Deploys to specified environment using GitHub Secrets

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        required: true
        type: choice
        options:
          - staging
          - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Read versions from config
        id: read-versions
        run: |
          if [ -f "factiiiAuto.yml" ]; then
            echo "✅ factiiiAuto.yml found"
            sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
            sudo chmod +x /usr/local/bin/yq
            NODE_VERSION=$(yq eval '.node_version // "20"' factiiiAuto.yml)
            PNPM_VERSION=$(yq eval '.pnpm_version // "8"' factiiiAuto.yml)
            echo "📦 Detected Node version: $NODE_VERSION"
            echo "📦 Detected pnpm version: $PNPM_VERSION"
          else
            echo "⚠️  factiiiAuto.yml not found, using defaults"
            NODE_VERSION="20"
            PNPM_VERSION="8"
          fi
          echo "node_version=$NODE_VERSION" >> $GITHUB_OUTPUT
          echo "pnpm_version=$PNPM_VERSION" >> $GITHUB_OUTPUT

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ steps.read-versions.outputs.pnpm_version }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ steps.read-versions.outputs.node_version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --ignore-scripts || echo "⚠️ Install failed, continuing with Docker build"
        continue-on-error: true

      - name: Run tests
        run: pnpm run test:server || echo "⚠️ Tests skipped"
        continue-on-error: true

      - name: Install yq
        run: |
          sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq

      - name: Read config
        id: read-config
        run: |
          if [ -f "factiii.yml" ]; then
            # Required settings
            REPO_NAME=$(yq eval '.name' factiii.yml)
            
            # AWS settings from factiii.yml (not secrets)
            AWS_ACCESS_KEY_ID=$(yq eval '.aws.access_key_id' factiii.yml)
            AWS_REGION=$(yq eval '.aws.region // "us-east-1"' factiii.yml)
            
            # Host from environments section
            STAGING_HOST=$(yq eval '.environments.staging.host // ""' factiii.yml)
            PROD_HOST=$(yq eval '.environments.production.host // ""' factiii.yml)
            
            # SSH user - check per-environment first, then factiiiAuto.yml, then default to ubuntu
            STAGING_SSH_USER=$(yq eval '.environments.staging.ssh_user // ""' factiii.yml)
            PROD_SSH_USER=$(yq eval '.environments.production.ssh_user // ""' factiii.yml)
            
            # Fallback to global ssh_user from factiiiAuto.yml if not set per-environment
            if [ -f "factiiiAuto.yml" ]; then
              GLOBAL_SSH_USER=$(yq eval '.ssh_user // "ubuntu"' factiiiAuto.yml | cut -d' ' -f1)
            else
              GLOBAL_SSH_USER="ubuntu"
            fi
            
            # Use per-environment user if set, otherwise use global
            STAGING_SSH_USER=${STAGING_SSH_USER:-$GLOBAL_SSH_USER}
            PROD_SSH_USER=${PROD_SSH_USER:-$GLOBAL_SSH_USER}
            
            # Dockerfile from factiiiAuto.yml
            if [ -f "factiiiAuto.yml" ]; then
              DOCKERFILE=$(yq eval '.dockerfile // "Dockerfile"' factiiiAuto.yml | cut -d' ' -f1)
            else
              DOCKERFILE="Dockerfile"
            fi
            
            # ECR settings
            ECR_REGISTRY=$(yq eval '.ecr_registry // ""' factiii.yml)
            ECR_REPOSITORY=$(yq eval '.ecr_repository // "apps"' factiii.yml)
            
            echo "repo_name=$REPO_NAME" >> $GITHUB_OUTPUT
            echo "aws_access_key_id=$AWS_ACCESS_KEY_ID" >> $GITHUB_OUTPUT
            echo "aws_region=$AWS_REGION" >> $GITHUB_OUTPUT
            echo "staging_host=$STAGING_HOST" >> $GITHUB_OUTPUT
            echo "prod_host=$PROD_HOST" >> $GITHUB_OUTPUT
            echo "staging_ssh_user=$STAGING_SSH_USER" >> $GITHUB_OUTPUT
            echo "prod_ssh_user=$PROD_SSH_USER" >> $GITHUB_OUTPUT
            echo "dockerfile=$DOCKERFILE" >> $GITHUB_OUTPUT
            echo "ecr_registry=$ECR_REGISTRY" >> $GITHUB_OUTPUT
            echo "ecr_repository=$ECR_REPOSITORY" >> $GITHUB_OUTPUT
          else
            echo "❌ factiii.yml not found"
            exit 1
          fi

      - name: Configure AWS credentials (production only)
        if: inputs.environment == 'production'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ steps.read-config.outputs.aws_access_key_id }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ steps.read-config.outputs.aws_region }}

      - name: Login to Amazon ECR (production only)
        if: inputs.environment == 'production'
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image to ECR (production only)
        if: inputs.environment == 'production'
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ steps.read-config.outputs.ecr_repository }}
          REPO_NAME: ${{ steps.read-config.outputs.repo_name }}
          DOCKERFILE: ${{ steps.read-config.outputs.dockerfile }}
        run: |
          echo "🔨 Building Docker image from $DOCKERFILE..."
          docker build --platform linux/amd64 -f $DOCKERFILE -t $ECR_REGISTRY/$ECR_REPOSITORY:${REPO_NAME}-production .
          
          echo "📤 Pushing to ECR..."
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:${REPO_NAME}-production
          
          echo "✅ Image pushed: $ECR_REGISTRY/$ECR_REPOSITORY:${REPO_NAME}-production"

      - name: Deploy to staging via SSH (direct build)
        if: inputs.environment == 'staging'
        env:
          SSH_KEY: ${{ secrets.STAGING_SSH }}
          SSH_HOST: ${{ steps.read-config.outputs.staging_host }}
          SSH_USER: ${{ steps.read-config.outputs.staging_ssh_user }}
          REPO_NAME: ${{ steps.read-config.outputs.repo_name }}
          GITHUB_REPO: ${{ github.repository }}
          GITHUB_BRANCH: ${{ github.ref_name }}
        run: |
          if [ -z "$SSH_KEY" ]; then
            echo "❌ Missing STAGING_SSH secret"
            exit 1
          fi
          
          if [ -z "$SSH_HOST" ]; then
            echo "❌ Missing host in factiii.yml: environments.staging.host"
            exit 1
          fi
          
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          
          echo "🚀 Deploying to staging server ($SSH_HOST)..."
          
          ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no "$SSH_USER@$SSH_HOST" bash -s << 'ENDSSH' "$REPO_NAME" "$GITHUB_REPO" "$GITHUB_BRANCH"
            set -e
            REPO_NAME=$1
            GITHUB_REPO=$2
            GITHUB_BRANCH=$3
            REPO_DIR=~/.factiii/$REPO_NAME
            
            # Ensure ~/.factiii exists
            mkdir -p ~/.factiii/scripts
            
            # Clone if doesn't exist
            if [ ! -d "$REPO_DIR" ]; then
              echo "📦 Cloning repo..."
              if ! git clone git@github.com:$GITHUB_REPO.git $REPO_DIR 2>&1; then
                echo ""
                echo "❌ Failed to clone repository"
                echo ""
                echo "The server needs SSH access to GitHub. Please:"
                echo "1. SSH to server: ssh $SSH_USER@$SSH_HOST"
                echo "2. Generate SSH key: ssh-keygen -t ed25519 -C 'factiii-deploy'"
                echo "3. Display public key: cat ~/.ssh/id_ed25519.pub"
                echo "4. Add key to GitHub: https://github.com/settings/keys"
                echo "5. Test access: ssh -T git@github.com"
                echo "6. Re-run: npx factiii deploy"
                exit 1
              fi
            fi
            
            cd $REPO_DIR
            
            echo "🔍 Checking dependencies..."
            
            # Check git
            if ! command -v git &> /dev/null; then
              echo "❌ git not found. Please install: brew install git"
              exit 1
            fi
            
            # Check node
            if ! command -v node &> /dev/null; then
              echo "❌ node not found. Please install: brew install node"
              exit 1
            fi
            
            # Check npm
            if ! command -v npm &> /dev/null; then
              echo "❌ npm not found. Please install: brew install node"
              exit 1
            fi
            
            # Check docker
            if ! command -v docker &> /dev/null; then
              echo "❌ docker not found. Please install: brew install --cask docker"
              exit 1
            fi
            
            # Check docker compose
            if ! docker compose version &> /dev/null; then
              echo "❌ docker compose not found. Please install Docker Desktop or: brew install docker-compose"
              exit 1
            fi
            
            # Install pnpm if needed
            if ! command -v pnpm &> /dev/null; then
              echo "📦 Installing pnpm..."
              npm install -g pnpm@9
            fi
            
            echo "✅ All dependencies available"
            
            echo "🔄 Pulling latest code..."
            git fetch
            git checkout $GITHUB_BRANCH
            git pull origin $GITHUB_BRANCH
            
            echo "📦 Installing dependencies..."
            pnpm install
            
            echo "🔨 Building Docker image..."
            cd ~/.factiii
            docker compose build ${REPO_NAME}-staging
            
            echo "🔄 Copying generate script..."
            # Copy generate-all.js from repo's node_modules/@factiii/stack if available
            if [ -f "$REPO_DIR/node_modules/@factiii/stack/src/scripts/generate-all.js" ]; then
              cp "$REPO_DIR/node_modules/@factiii/stack/src/scripts/generate-all.js" ~/.factiii/scripts/
            fi
            
            echo "🔄 Regenerating shared configs..."
            cd ~/.factiii
            if [ -f "scripts/generate-all.js" ]; then
              node scripts/generate-all.js
            else
              echo "⚠️  generate-all.js not found, skipping config generation"
            fi
            
            echo "🚀 Deploying..."
            docker compose up -d ${REPO_NAME}-staging
            
            echo "✅ Staging deployment complete!"
          ENDSSH
          
          rm -f ~/.ssh/deploy_key

      - name: Deploy to production via SSH (ECR pull)
        if: inputs.environment == 'production'
        env:
          SSH_KEY: ${{ secrets.PROD_SSH }}
          SSH_HOST: ${{ steps.read-config.outputs.prod_host }}
          SSH_USER: ${{ steps.read-config.outputs.prod_ssh_user }}
          REPO_NAME: ${{ steps.read-config.outputs.repo_name }}
          GITHUB_REPO: ${{ github.repository }}
          GITHUB_BRANCH: ${{ github.ref_name }}
        run: |
          if [ -z "$SSH_KEY" ]; then
            echo "❌ Missing PROD_SSH secret"
            exit 1
          fi
          
          if [ -z "$SSH_HOST" ]; then
            echo "❌ Missing host in factiii.yml: environments.production.host"
            exit 1
          fi
          
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          
          echo "🚀 Deploying to production server ($SSH_HOST)..."
          
          ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no "$SSH_USER@$SSH_HOST" bash -s << 'ENDSSH' "$REPO_NAME" "$GITHUB_REPO" "$GITHUB_BRANCH"
            set -e
            REPO_NAME=$1
            GITHUB_REPO=$2
            GITHUB_BRANCH=$3
            REPO_DIR=~/.factiii/$REPO_NAME
            
            # Ensure ~/.factiii exists
            mkdir -p ~/.factiii/scripts
            
            # Clone if doesn't exist (need factiii.yml)
            if [ ! -d "$REPO_DIR" ]; then
              echo "📦 Cloning repo..."
              if ! git clone git@github.com:$GITHUB_REPO.git $REPO_DIR 2>&1; then
                echo ""
                echo "❌ Failed to clone repository"
                echo ""
                echo "The server needs SSH access to GitHub. Please:"
                echo "1. SSH to server: ssh $SSH_USER@$SSH_HOST"
                echo "2. Generate SSH key: ssh-keygen -t ed25519 -C 'factiii-deploy'"
                echo "3. Display public key: cat ~/.ssh/id_ed25519.pub"
                echo "4. Add key to GitHub: https://github.com/settings/keys"
                echo "5. Test access: ssh -T git@github.com"
                echo "6. Re-run: npx factiii deploy"
                exit 1
              fi
            fi
            
            cd $REPO_DIR
            
            echo "🔄 Pulling latest code (for configs)..."
            git fetch
            git checkout $GITHUB_BRANCH
            git pull origin $GITHUB_BRANCH
            
            echo "🔄 Copying generate script..."
            # Copy generate-all.js from repo's node_modules/@factiii/stack if available
            if [ -f "$REPO_DIR/node_modules/@factiii/stack/src/scripts/generate-all.js" ]; then
              cp "$REPO_DIR/node_modules/@factiii/stack/src/scripts/generate-all.js" ~/.factiii/scripts/
            fi
            
            echo "📥 Pulling Docker image from ECR..."
            cd ~/.factiii
            docker compose pull ${REPO_NAME}-prod
            
            echo "🔄 Regenerating shared configs..."
            if [ -f "scripts/generate-all.js" ]; then
              node scripts/generate-all.js
            else
              echo "⚠️  generate-all.js not found, skipping config generation"
            fi
            
            echo "🚀 Deploying..."
            docker compose up -d ${REPO_NAME}-prod
            
            echo "✅ Production deployment complete!"
          ENDSSH
          
          rm -f ~/.ssh/deploy_key

      - name: Run Prisma migrations (production only)
        if: inputs.environment == 'production'
        env:
          SSH_KEY: ${{ secrets.PROD_SSH }}
          SSH_HOST: ${{ steps.read-config.outputs.prod_host }}
          SSH_USER: ${{ steps.read-config.outputs.ssh_user }}
          REPO_NAME: ${{ steps.read-config.outputs.repo_name }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          
          echo "🔄 Running database migrations..."
          
          ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no "$SSH_USER@$SSH_HOST" bash << 'ENDSSH'
            cd ~/.factiii/${REPO_NAME}
            
            # Read Prisma config from factiiiAuto.yml
            if [ -f "factiiiAuto.yml" ]; then
              PRISMA_SCHEMA=$(grep '^prisma_schema:' factiiiAuto.yml | cut -d: -f2 | tr -d ' ' || echo "prisma/schema.prisma")
              PRISMA_VERSION=$(grep '^prisma_version:' factiiiAuto.yml | cut -d: -f2 | tr -d ' ' || echo "latest")
            else
              PRISMA_SCHEMA="prisma/schema.prisma"
              PRISMA_VERSION="latest"
            fi
            
            echo "   Schema: $PRISMA_SCHEMA"
            echo "   Version: $PRISMA_VERSION"
            
            cd ~/.factiii
            docker compose run --rm --no-deps ${REPO_NAME}-prod \
              npx -y prisma@${PRISMA_VERSION} migrate deploy --schema=${PRISMA_SCHEMA} || true
          ENDSSH
          
          rm -f ~/.ssh/deploy_key

      - name: Run health check
        env:
          ENVIRONMENT: ${{ inputs.environment }}
          SSH_USER: ${{ steps.read-config.outputs.ssh_user }}
          SSH_KEY: ${{ inputs.environment == 'staging' && secrets.STAGING_SSH || secrets.PROD_SSH }}
          SSH_HOST: ${{ inputs.environment == 'staging' && steps.read-config.outputs.staging_host || steps.read-config.outputs.prod_host }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          
          echo "🏥 Running health check..."
          HEALTH_CHECK_PASSED=false
          
          for i in {1..10}; do
            if ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no \
              "$SSH_USER@$SSH_HOST" \
              "curl -f -s http://localhost:3000/health > /dev/null 2>&1"; then
              echo "✅ Health check passed!"
              HEALTH_CHECK_PASSED=true
              break
            fi
            echo "⏳ Waiting for service to be ready (attempt $i/10)..."
            sleep 5
          done
          
          rm -f ~/.ssh/deploy_key
          
          if [ "$HEALTH_CHECK_PASSED" = false ]; then
            echo "⚠️  Health check failed, but deployment completed"
            echo "   Check server logs for details"
          fi
