name: Staging CI/CD

# Application deployment workflow for staging environment
# Runs tests, builds Docker image, and deploys to staging server

on:
  pull_request:
    branches: [staging]
  push:
    branches: [staging]

env:
  NODE_VERSION: '20'

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: pnpm test

      - name: Run integration tests (if available)
        run: pnpm run test:integration --if-present
        continue-on-error: false

      - name: Build Docker image for staging
        run: pnpm run build:docker:staging

  deploy-staging:
    needs: test-and-build
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY || 'apps' }}
          IMAGE_TAG: staging-${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:staging-latest
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:staging-latest

      - name: Deploy to staging server
        env:
          SSH_KEY: ${{ secrets.STAGING_SSH }}
          SSH_HOST: ${{ secrets.STAGING_HOST }}
          SSH_USER: ${{ secrets.STAGING_USER || 'ubuntu' }}
          REPO_NAME: ${{ github.event.repository.name }}
        run: |
          if [ -z "$SSH_KEY" ] || [ -z "$SSH_HOST" ]; then
            echo "❌ Missing SSH credentials for staging"
            exit 1
          fi
          
          echo "$SSH_KEY" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          
          SERVICE_KEY="${REPO_NAME}-staging"
          
          echo "🚀 Deploying to staging server..."
          ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no \
            "$SSH_USER@$SSH_HOST" \
            "cd ~/infrastructure && \
             docker compose pull ${SERVICE_KEY} && \
             docker compose up -d ${SERVICE_KEY}"
          
          echo "✅ Deployment complete!"
          
          rm -f ~/.ssh/deploy_key

      - name: Run health check
        env:
          STAGING_URL: ${{ secrets.STAGING_URL }}
        run: |
          if [ -n "$STAGING_URL" ]; then
            echo "🏥 Running health check..."
            for i in {1..10}; do
              if curl -f -s "${STAGING_URL}/health" > /dev/null; then
                echo "✅ Health check passed!"
                exit 0
              fi
              echo "⏳ Waiting for service to be ready (attempt $i/10)..."
              sleep 5
            done
            echo "❌ Health check failed after 10 attempts"
            exit 1
          else
            echo "⚠️  STAGING_URL not set, skipping health check"
          fi
