/**
 * Generate stack.yml
 *
 * Auto-detects project configuration and generates stack.yml.
 */

import * as fs from 'fs';
import * as path from 'path';
import yaml from 'js-yaml';
import { execSync } from 'child_process';

import { STACK_CONFIG_FILENAME } from '../constants/config-files.js';

/**
 * Read package.json from a directory
 */
function readPackageJson(rootDir: string): Record<string, unknown> | null {
  const pkgPath = path.join(rootDir, 'package.json');
  if (!fs.existsSync(pkgPath)) return null;
  try {
    return JSON.parse(fs.readFileSync(pkgPath, 'utf8')) as Record<string, unknown>;
  } catch {
    return null;
  }
}

/**
 * Try to detect github_repo from git remote origin
 */
function detectGithubRepo(rootDir: string): string | null {
  try {
    const remote = execSync('git remote get-url origin', {
      cwd: rootDir,
      encoding: 'utf8',
      stdio: ['pipe', 'pipe', 'pipe'],
    }).trim();
    // Match github.com:user/repo.git or github.com/user/repo.git
    const match = remote.match(/github\.com[:/](.+?)(?:\.git)?$/);
    if (match && match[1]) return match[1];
  } catch {
    // Not a git repo or no remote
  }
  return null;
}

/**
 * Detect the dev machine OS
 */
function detectServerOS(): 'mac' | 'ubuntu' | 'windows' {
  if (process.platform === 'darwin') return 'mac';
  if (process.platform === 'win32') return 'windows';
  return 'ubuntu';
}

/**
 * Generate stack.yml by auto-detecting project configuration.
 * Auto-detects: name, github_repo, pipeline, staging/prod, frameworks.
 * Uses EXAMPLE_ prefix for values that cannot be auto-detected (domains, ssl_email).
 *
 * @param rootDir - Project root directory
 * @param options - Optional settings (force: overwrite existing file)
 */
export function generateSmartStackYml(rootDir: string, options: { force?: boolean } = {}): boolean {
  const outputPath = path.join(rootDir, STACK_CONFIG_FILENAME);

  // Check if file already exists
  if (fs.existsSync(outputPath) && !options.force) {
    console.log('[OK] ' + STACK_CONFIG_FILENAME + ' already exists (use --force to overwrite)');
    return false;
  }

  // Read package.json for name and framework detection
  const pkg = readPackageJson(rootDir);
  const deps: Record<string, string> = {
    ...(pkg?.dependencies as Record<string, string> ?? {}),
    ...(pkg?.devDependencies as Record<string, string> ?? {}),
  };

  // Detect project name
  const pkgName = pkg?.name as string | undefined;
  const dirName = path.basename(rootDir);
  const name = (pkgName ?? dirName).replace(/[^a-z0-9-]/gi, '-').toLowerCase();

  // Detect github repo
  const githubRepo = detectGithubRepo(rootDir) ?? 'EXAMPLE_username/' + name;

  // Detect server OS for staging
  const devOS = detectServerOS();
  const stagingServer = devOS === 'windows' ? 'ubuntu' : devOS;

  // Build config
  const config: Record<string, unknown> = {
    name,
    config_version: '0.1.0',
    github_repo: githubRepo,
    ssl_email: 'EXAMPLE_admin@yourdomain.com',
    pipeline: 'factiii',

    staging: {
      server: stagingServer,
      domain: 'EXAMPLE_staging.yourdomain.com',
      env_file: '.env.staging',
    },

    prod: {
      server: 'ubuntu',
      domain: 'EXAMPLE_yourdomain.com',
      env_file: '.env.prod',
      config: 'free-tier',
      access_key_id: 'EXAMPLE_AKIAXXXXXXXX',
      region: 'us-east-1',
    },

  };

  // Detect frameworks and add relevant config
  const detectedPlugins: string[] = [];
  if (deps['next']) detectedPlugins.push('nextjs');
  if (deps['prisma'] || deps['@prisma/client']) detectedPlugins.push('prisma');
  if (deps['@trpc/server']) detectedPlugins.push('trpc');
  if (deps['expo']) detectedPlugins.push('expo');

  // Build YAML content with comments
  const sections: string[] = [];

  sections.push('# Generated by @factiii/stack');
  sections.push('# Replace all EXAMPLE_ values with your actual configuration');
  sections.push('');

  // Dump main config
  sections.push(yaml.dump(config, { lineWidth: -1, noRefs: true }).trim());
  sections.push('');

  // Add detected plugins as a comment
  if (detectedPlugins.length > 0) {
    sections.push('# Detected frameworks: ' + detectedPlugins.join(', '));
    sections.push('');
  }

  // OpenClaw / Moltbot - commented out by default
  sections.push('# ============================================================');
  sections.push('# OPENCLAW (MOLTBOT)');
  sections.push('# ============================================================');
  sections.push('# Autonomous AI coding agent that runs locally inside a Tart VM');
  sections.push('# with Ollama (local LLM). Keeps your code and data on your machine.');
  sections.push('# Requires macOS with Apple Silicon.');
  sections.push('#');
  sections.push('# To enable, uncomment the line below and run: npx stack fix --dev');
  sections.push('# openclaw: true');
  sections.push('');

  // Add helpful comments
  sections.push('# ============================================================');
  sections.push('# NEXT STEPS');
  sections.push('# ============================================================');
  sections.push('#');
  sections.push('# 1. UPDATE THIS FILE');
  sections.push('#    Replace all values marked EXAMPLE_ with your actual values:');
  sections.push('#    - ssl_email: your real email for SSL certificates');
  sections.push('#    - staging.domain: your staging domain');
  sections.push('#    - prod.domain: your production domain');
  sections.push('#');
  sections.push('# 2. SCAN FOR ISSUES');
  sections.push('#    npx stack scan           -> checks everything, reports what is missing (changes nothing)');
  sections.push('#');
  sections.push('# 3. AUTO-FIX ISSUES');
  sections.push('#    npx stack fix            -> installs tools, creates config files, fixes what it can');
  sections.push('#                                (does NOT touch docker/nginx - those are handled by deploy)');
  sections.push('#');
  sections.push('# 4. SET UP SECRETS');
  sections.push('#    npx stack deploy --secrets set  -> store SSH keys & credentials in Ansible Vault');
  sections.push('#');
  sections.push('# 5. DEPLOY');
  sections.push('#    npx stack deploy --staging --dry-run   -> preview what will happen');
  sections.push('#    npx stack deploy --staging             -> deploy to staging');
  sections.push('#    npx stack deploy --prod                -> deploy to production');
  sections.push('#');
  sections.push('# ============================================================');
  sections.push('');

  const finalContent = sections.join('\n');
  fs.writeFileSync(outputPath, finalContent);

  console.log('[OK] Created ' + STACK_CONFIG_FILENAME + ' (auto-detected: ' + name + ')');

  if (detectedPlugins.length > 0) {
    console.log('     Detected: ' + detectedPlugins.join(', '));
  }

  return true;
}
