/**
 * Stack Version Pin Scanfix
 *
 * Dev-only guardrail for the dev-direct deploy model. Since the dev machine is
 * the sole source of truth for generated docker-compose.yml / nginx.conf shipped
 * to prod, a stale `@factiii/stack` CLI here silently ships a bad artifact.
 *
 * The pin lives in stackAuto.yml under `stack_version`. It's auto-bootstrapped
 * on first run, then becomes the contract for every subsequent dev machine:
 *   - pin missing → fix writes it (first-run bootstrap)
 *   - pin matches → no issue
 *   - pin mismatches → critical, fix=null (user bumps `@factiii/stack` or the pin)
 *
 * Runs only on dev. If dev fails this check, scan blocks the whole chain —
 * deploy never touches staging or prod with the wrong CLI.
 */

import * as fs from 'fs';
import * as path from 'path';
import yaml from 'js-yaml';

import type { FactiiiConfig, Fix } from '../../../../types/index.js';
import { hasEnvironments } from '../../../../utils/config-helpers.js';

function getInstalledStackVersion(): string {
  // dist/plugins/pipelines/factiii/scanfix → package root is 5 levels up at runtime.
  // Walk up until we find the @factiii/stack package.json, same pattern as
  // generate-stack-auto.ts uses.
  let dir = __dirname;
  for (let i = 0; i < 6; i++) {
    const pkgPath = path.join(dir, 'package.json');
    if (fs.existsSync(pkgPath)) {
      try {
        const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf8')) as { name?: string; version?: string };
        if (pkg.name === '@factiii/stack' && pkg.version) return pkg.version;
      } catch {
        // keep walking
      }
    }
    dir = path.dirname(dir);
  }
  return '0.0.0';
}

function getStackAutoPath(rootDir: string): string | null {
  const candidates = ['stackAuto.yml', 'factiiiAuto.yml'];
  for (const name of candidates) {
    const p = path.join(rootDir, name);
    if (fs.existsSync(p)) return p;
  }
  return null;
}

function readPinnedVersion(rootDir: string): string | null {
  const p = getStackAutoPath(rootDir);
  if (!p) return null;
  try {
    const doc = yaml.load(fs.readFileSync(p, 'utf8')) as Record<string, unknown> | null;
    const pinned = doc?.stack_version;
    return typeof pinned === 'string' && pinned.length > 0 ? pinned : null;
  } catch {
    return null;
  }
}

function writePinnedVersion(rootDir: string, version: string): void {
  // Prefer stackAuto.yml; fall back to factiiiAuto.yml if that's the one in use.
  const existing = getStackAutoPath(rootDir);
  const target = existing ?? path.join(rootDir, 'stackAuto.yml');
  let doc: Record<string, unknown> = {};
  if (existing) {
    try {
      doc = (yaml.load(fs.readFileSync(existing, 'utf8')) as Record<string, unknown>) ?? {};
    } catch {
      doc = {};
    }
  }
  doc.stack_version = version;
  fs.writeFileSync(target, '# Generated by @factiii/stack v' + version + '\n' + yaml.dump(doc, { lineWidth: -1 }), 'utf8');
}

export const stackVersionPinFixes: Fix[] = [
  {
    id: 'stack-version-pin-missing',
    stage: 'dev',
    severity: 'info',
    description: '📌 stack_version pin missing in stackAuto.yml',
    scan: async (config: FactiiiConfig, rootDir: string): Promise<boolean> => {
      // Version pin is a dev-machine contract; on-server runs don't need to re-pin.
      if (process.env.FACTIII_ON_SERVER === 'true' || process.env.GITHUB_ACTIONS === 'true') return false;
      // Only relevant once the project has real environments that deploy anywhere.
      if (!hasEnvironments(config)) return false;
      return readPinnedVersion(rootDir) === null;
    },
    fix: async (_config: FactiiiConfig, rootDir: string): Promise<boolean> => {
      writePinnedVersion(rootDir, getInstalledStackVersion());
      return true;
    },
    manualFix: 'Add `stack_version: ' + getInstalledStackVersion() + '` to stackAuto.yml',
  },

  {
    id: 'stack-version-pin-mismatch',
    stage: 'dev',
    severity: 'critical',
    description: '📌 Installed @factiii/stack version does not match stack_version pin',
    scan: async (config: FactiiiConfig, rootDir: string): Promise<boolean> => {
      if (process.env.FACTIII_ON_SERVER === 'true' || process.env.GITHUB_ACTIONS === 'true') return false;
      if (!hasEnvironments(config)) return false;
      const pinned = readPinnedVersion(rootDir);
      if (!pinned) return false; // handled by the -missing fix above
      return pinned !== getInstalledStackVersion();
    },
    fix: null,
    manualFix:
      'Either bump your installed CLI to match the pin:  pnpm update @factiii/stack@' +
      '<pinned-version>\n' +
      '   Or, if the new version is intentional, update `stack_version` in stackAuto.yml to ' +
      getInstalledStackVersion() + '.',
  },
];
