/**
 * Init Command
 *
 * Scans the codebase and creates stack.yml with auto-detected settings
 * and EXAMPLE_ placeholder values for the user to fill in.
 *
 * This command only initializes config files — it does not fix anything.
 * Vault setup, secrets, and all other fixes are handled by scanfixes
 * in the factiii pipeline (run: npx stack scan / npx stack fix).
 */

import * as fs from 'fs';
import { STACK_CONFIG_FILENAME, STACK_LOCAL_FILENAME, getStackConfigPath, getStackLocalPath } from '../constants/config-files.js';
import { generateSmartStackYml } from '../generators/generate-stack-yml.js';
import { generateFactiiiAuto } from '../generators/generate-stack-auto.js';
import { ensureGitignored } from '../utils/gitignore.js';
import type { InitOptions } from '../types/index.js';

export async function init(options: InitOptions = {}): Promise<void> {
  const rootDir = options.rootDir ?? process.cwd();
  const configPath = getStackConfigPath(rootDir);
  const isFirstRun = !fs.existsSync(configPath);

  if (options.force) {
    console.log('Regenerating ' + STACK_CONFIG_FILENAME + '...\n');
    generateSmartStackYml(rootDir, { force: true });
    await generateFactiiiAuto(rootDir, { force: true });
  } else if (isFirstRun) {
    console.log('Scanning codebase...\n');
    const created = generateSmartStackYml(rootDir);
    if (created) {
      await generateFactiiiAuto(rootDir);
      console.log('');
      console.log('  ' + STACK_CONFIG_FILENAME + ' is the configuration for everything.');
      console.log('  Update the vars marked with EXAMPLE_ before proceeding.');
      console.log('');
    }
  } else {
    console.log('[OK] ' + STACK_CONFIG_FILENAME + ' already exists');
    console.log('     (use --force to regenerate)\n');
  }

  // Create or reset stack.local.yml with dev_only: true
  const localPath = getStackLocalPath(rootDir);
  const devOS = process.platform === 'darwin' ? 'mac' : process.platform === 'win32' ? 'windows' : 'ubuntu';
  if (!fs.existsSync(localPath)) {
    const content =
      '# Local machine config (gitignored - each developer has their own)\n' +
      '# Generated by: npx stack init\n\n' +
      'dev_os: ' + devOS + '\n\n' +
      '# Dev-only mode (default: true)\n' +
      '# When true, only --dev stage is allowed.\n' +
      '# Set to false to unlock staging/prod stages:\n' +
      '#   npx stack scan --staging   (auto-unlocks on first run)\n' +
      '#   or manually change to: dev_only: false\n' +
      'dev_only: true\n\n' +
      '# Claude Code skills (opt-in, default: off)\n' +
      '# When true, `npx stack fix --dev` installs factiii Claude Code skills\n' +
      '# (e.g. prod-check) into ~/.claude/skills/ on this machine. Off by default\n' +
      '# because ~/.claude/ is your personal Claude config — stack will not write\n' +
      '# to your home directory unless you ask it to. Existing hand-edited skill\n' +
      '# files are never overwritten; delete one to refresh it.\n' +
      '# Uncomment and set true to enable:\n' +
      '# claude_skills: true\n';
    fs.writeFileSync(localPath, content, 'utf8');
    console.log('  [OK] Created ' + STACK_LOCAL_FILENAME + ' (dev_os: ' + devOS + ', dev_only: true)');
  } else {
    // Ensure dev_only: true is set (init always resets to safe default)
    let localContent = fs.readFileSync(localPath, 'utf8');
    if (localContent.includes('dev_only: false')) {
      localContent = localContent.replace('dev_only: false', 'dev_only: true');
      fs.writeFileSync(localPath, localContent, 'utf8');
      console.log('  [OK] Reset dev_only to true in ' + STACK_LOCAL_FILENAME);
    } else if (!localContent.includes('dev_only:')) {
      localContent = localContent.trimEnd() + '\n\n' +
        '# Dev-only mode (default: true)\n' +
        '# When true, only --dev stage is allowed.\n' +
        '# Set to false to unlock staging/prod stages:\n' +
        '#   npx stack scan --staging   (auto-unlocks on first run)\n' +
        '#   or manually change to: dev_only: false\n' +
        'dev_only: true\n';
      fs.writeFileSync(localPath, localContent, 'utf8');
      console.log('  [OK] Added dev_only: true to ' + STACK_LOCAL_FILENAME);
    } else {
      console.log('  [OK] ' + STACK_LOCAL_FILENAME + ' (dev_only: true)');
    }

    // Append the claude_skills opt-in stub if it's missing entirely.
    // We never flip an existing setting — only document the option for devs
    // who haven't seen it yet.
    if (!localContent.includes('claude_skills')) {
      localContent = localContent.trimEnd() + '\n\n' +
        '# Claude Code skills (opt-in, default: off)\n' +
        '# When true, `npx stack fix --dev` installs factiii Claude Code skills\n' +
        '# (e.g. prod-check) into ~/.claude/skills/ on this machine. Off by default\n' +
        '# because ~/.claude/ is your personal Claude config — stack will not write\n' +
        '# to your home directory unless you ask it to. Existing hand-edited skill\n' +
        '# files are never overwritten; delete one to refresh it.\n' +
        '# Uncomment and set true to enable:\n' +
        '# claude_skills: true\n';
      fs.writeFileSync(localPath, localContent, 'utf8');
      console.log('  [OK] Added claude_skills opt-in stub to ' + STACK_LOCAL_FILENAME);
    }
  }
  console.log('');
  console.log('  dev_only is enabled — only --dev stage will run.');
  console.log('  To unlock staging/prod, either:');
  console.log('    - Run: npx stack scan --staging   (auto-unlocks)');
  console.log('    - Edit ' + STACK_LOCAL_FILENAME + ' and set dev_only: false');

  // Ensure gitignore entries for sensitive files
  ensureGitignored(rootDir, STACK_LOCAL_FILENAME);
  ensureGitignored(rootDir, '.env.staging');
  ensureGitignored(rootDir, '.env.prod');

  console.log('  ────────────────────────────────────────────────');
  console.log('  NEXT STEPS');
  console.log('  ────────────────────────────────────────────────');
  console.log('');
  console.log('  1. Edit ' + STACK_CONFIG_FILENAME + ' — add staging/prod server config');
  console.log('  2. npx stack fix --staging    -> setup vault + SSH + server');
  console.log('  3. npx stack deploy --staging -> deploy app');
  console.log('');
}

export default init;
