/**
 * Tests for the single-tenant prod generators used by dev-direct deploy.
 */
import yaml from 'js-yaml';

import {
  generateProdCompose,
  generateProdNginx,
  prodComposeServiceName,
} from '../src/generators/index.js';
import type { FactiiiConfig, EnvironmentConfig } from '../src/types/index.js';

const baseConfig: FactiiiConfig = {
  name: 'factiii',
};

const prodEnv: EnvironmentConfig = {
  server: 'ubuntu',
  domain: 'factiii.com',
};

describe('generateProdCompose', () => {
  it('emits the banner + app + postgres + nginx services', () => {
    const out = generateProdCompose(baseConfig, {
      stage: 'prod',
      imageTag: 'ghcr.io/factiii/factiii:latest',
      envConfig: prodEnv,
      stackVersion: '0.9.0',
    });

    expect(out.startsWith('# Generated by @factiii/stack v0.9.0')).toBe(true);

    const body = out.replace(/^# [^\n]*\n/, '');
    const parsed = yaml.load(body) as { services: Record<string, { image?: string; container_name?: string; ports?: string[] }> };

    expect(parsed.services.postgres).toBeDefined();
    expect(parsed.services.nginx).toBeDefined();
    expect(parsed.services.nginx?.ports).toEqual(['80:80', '443:443']);

    const appService = parsed.services['factiii-prod'];
    expect(appService).toBeDefined();
    expect(appService?.image).toBe('ghcr.io/factiii/factiii:latest');
    expect(appService?.container_name).toBe('factiii-prod');
  });

  it('derives the app service name from name + stage', () => {
    expect(prodComposeServiceName({ name: 'greasemoto' } as FactiiiConfig, 'prod')).toBe('greasemoto-prod');
    expect(prodComposeServiceName({ name: 'app' } as FactiiiConfig, 'prod')).toBe('app-prod');
  });

  it('falls back to the unversioned banner when no stackVersion is supplied', () => {
    const out = generateProdCompose(baseConfig, {
      stage: 'prod',
      imageTag: 'img:latest',
      envConfig: prodEnv,
    });
    expect(out.startsWith('# Generated by @factiii/stack\n')).toBe(true);
    expect(out.startsWith('# Generated by @factiii/stack v')).toBe(false);
  });
});

describe('generateProdNginx', () => {
  it('embeds the domain and proxies to the app service name', () => {
    const out = generateProdNginx(baseConfig, {
      stage: 'prod',
      domain: 'factiii.com',
      stackVersion: '0.9.0',
    });
    expect(out.startsWith('# Generated by @factiii/stack v0.9.0')).toBe(true);
    expect(out).toContain('server_name factiii.com;');
    expect(out).toContain('proxy_pass http://factiii-prod:3000;');
    expect(out).toContain('/.well-known/acme-challenge/');
  });

  it('uses the app service name derived from config.name', () => {
    const out = generateProdNginx({ name: 'greasemoto' } as FactiiiConfig, {
      stage: 'prod',
      domain: 'greasemoto.com',
    });
    expect(out).toContain('proxy_pass http://greasemoto-prod:3000;');
  });
});
