/**
 * Bootstrap Scanfixes
 *
 * Creates config files (stack.yml, stackAuto.yml, stack.local.yml) and
 * ensures gitignore entries for sensitive files. These run first in the
 * factiii pipeline's fixes array so that other scanfixes can rely on
 * config files existing.
 */

import * as fs from 'fs';

import { STACK_CONFIG_FILENAME, STACK_LOCAL_FILENAME, STACK_AUTO_FILENAME, getStackConfigPath, getStackAutoPath, getStackLocalPath } from '../../../../constants/config-files.js';
import { ensureGitignored, isGitignored } from '../../../../utils/gitignore.js';
import type { Fix, FactiiiConfig } from '../../../../types/index.js';

/**
 * Detect the dev OS from process.platform
 */
function detectDevOS(): 'mac' | 'windows' | 'ubuntu' {
  if (process.platform === 'darwin') return 'mac';
  if (process.platform === 'win32') return 'windows';
  return 'ubuntu';
}

export const bootstrapFixes: Fix[] = [
  // ── Config file creation ───────────────────────────────────────
  {
    id: 'missing-stack-yml',
    stage: 'dev',
    severity: 'critical',
    description: '📋 ' + STACK_CONFIG_FILENAME + ' not found',
    scan: async (_config: FactiiiConfig, rootDir: string): Promise<boolean> => {
      return !fs.existsSync(getStackConfigPath(rootDir));
    },
    fix: async (_config: FactiiiConfig, rootDir: string): Promise<boolean> => {
      // Use dynamic import to avoid circular dependency
      const { generateSmartStackYml } = await import('../../../../generators/generate-stack-yml.js');
      return generateSmartStackYml(rootDir);
    },
    manualFix: 'Run: npx stack fix',
  },

  {
    id: 'missing-stack-auto-yml',
    stage: 'dev',
    severity: 'critical',
    description: '📋 ' + STACK_AUTO_FILENAME + ' not found',
    scan: async (_config: FactiiiConfig, rootDir: string): Promise<boolean> => {
      return !fs.existsSync(getStackAutoPath(rootDir));
    },
    fix: async (_config: FactiiiConfig, rootDir: string): Promise<boolean> => {
      const { generateFactiiiAuto } = await import('../../../../generators/generate-stack-auto.js');
      await generateFactiiiAuto(rootDir, { force: true });
      return true;
    },
    manualFix: 'Run: npx stack fix',
  },

  {
    id: 'missing-stack-local-yml',
    stage: 'dev',
    severity: 'warning',
    description: '💻 ' + STACK_LOCAL_FILENAME + ' not found (specifies your dev OS)',
    scan: async (_config: FactiiiConfig, rootDir: string): Promise<boolean> => {
      return !fs.existsSync(getStackLocalPath(rootDir));
    },
    fix: async (_config: FactiiiConfig, rootDir: string): Promise<boolean> => {
      const localPath = getStackLocalPath(rootDir);
      const devOS = detectDevOS();
      const content =
        '# Local machine config (gitignored - each developer has their own)\n' +
        '# Generated by: npx stack\n' +
        '\n' +
        'dev_os: ' + devOS + '\n';
      fs.writeFileSync(localPath, content, 'utf8');
      // Also ensure gitignored
      ensureGitignored(rootDir, STACK_LOCAL_FILENAME);
      ensureGitignored(rootDir, 'factiii.local.yml');
      console.log('  [OK] Created ' + STACK_LOCAL_FILENAME + ' (dev_os: ' + devOS + ')');
      return true;
    },
    manualFix: 'Create ' + STACK_LOCAL_FILENAME + ' with: dev_os: mac|windows|ubuntu',
  },

  // ── Gitignore checks ──────────────────────────────────────────
  {
    id: 'gitignore-local-config',
    stage: 'dev',
    severity: 'info',
    description: '🙈 ' + STACK_LOCAL_FILENAME + ' not in .gitignore',
    scan: async (_config: FactiiiConfig, rootDir: string): Promise<boolean> => {
      // Only check if the file exists (no point gitignoring something that doesn't exist)
      if (!fs.existsSync(getStackLocalPath(rootDir))) return false;
      return !isGitignored(rootDir, STACK_LOCAL_FILENAME);
    },
    fix: async (_config: FactiiiConfig, rootDir: string): Promise<boolean> => {
      ensureGitignored(rootDir, STACK_LOCAL_FILENAME);
      ensureGitignored(rootDir, 'factiii.local.yml');
      return true;
    },
    manualFix: 'Add ' + STACK_LOCAL_FILENAME + ' to .gitignore',
  },

  {
    id: 'gitignore-env-staging',
    stage: 'dev',
    severity: 'info',
    description: '🙈 .env.staging not in .gitignore',
    scan: async (_config: FactiiiConfig, rootDir: string): Promise<boolean> => {
      const envPath = require('path').join(rootDir, '.env.staging');
      if (!fs.existsSync(envPath)) return false;
      return !isGitignored(rootDir, '.env.staging');
    },
    fix: async (_config: FactiiiConfig, rootDir: string): Promise<boolean> => {
      ensureGitignored(rootDir, '.env.staging');
      return true;
    },
    manualFix: 'Add .env.staging to .gitignore',
  },

  {
    id: 'gitignore-env-prod',
    stage: 'dev',
    severity: 'info',
    description: '🙈 .env.prod not in .gitignore',
    scan: async (_config: FactiiiConfig, rootDir: string): Promise<boolean> => {
      const envPath = require('path').join(rootDir, '.env.prod');
      if (!fs.existsSync(envPath)) return false;
      return !isGitignored(rootDir, '.env.prod');
    },
    fix: async (_config: FactiiiConfig, rootDir: string): Promise<boolean> => {
      ensureGitignored(rootDir, '.env.prod');
      return true;
    },
    manualFix: 'Add .env.prod to .gitignore',
  },
];
