/**
 * start.sh scanfix for Factiii Pipeline plugin
 *
 * Merges slot-based env setup into existing start.sh:
 * - If start.sh exists: injects IP detection + slot scan + PORT injection
 *   between marker comments at the TOP, preserving all existing logic below
 * - If no start.sh: generates a full quick-start script
 *
 * On re-run, only the section between markers is replaced (idempotent).
 */

import * as fs from 'fs';
import * as path from 'path';
import type { FactiiiConfig, Fix } from '../../../../types/index.js';
import { hasEnvironments } from '../../../../utils/config-helpers.js';
import { getFactiiiVersion } from '../../../../utils/version-check.js';

const MARKER_BEGIN = '# ── @factiii/stack slot setup BEGIN ──';
const MARKER_END = '# ── @factiii/stack slot setup END ──';

/**
 * Generate the slot setup section (IP detection + sibling scan + PORT + .env injection)
 * This is the block that gets injected between markers.
 */
function generateSlotSection(): string {
  const version = getFactiiiVersion();

  return MARKER_BEGIN + '\n' +
    '# Generated by @factiii/stack v' + version + '\n' +
    '# PORT slot system: PORT=N where N=1-5\n' +
    '#   Client port = 3000 + N (e.g. slot 1 = 3001)\n' +
    '#   Server port = 5000 + N (e.g. slot 1 = 5001)\n' +
    '#\n' +
    '# This section is auto-managed. Edit code BELOW the END marker.\n' +
    '\n' +
    '# ── Detect system IP ──────────────────────────────────────\n' +
    'detect_ip() {\n' +
    '  local ip=""\n' +
    '  case "$(uname -s)" in\n' +
    '    Darwin)\n' +
    '      ip=$(ipconfig getifaddr en0 2>/dev/null || ipconfig getifaddr en1 2>/dev/null || echo "")\n' +
    '      ;;\n' +
    '    Linux)\n' +
    '      ip=$(hostname -I 2>/dev/null | awk \'{print $1}\' || echo "")\n' +
    '      ;;\n' +
    '    MINGW*|MSYS*|CYGWIN*)\n' +
    '      ip=$(ipconfig 2>/dev/null | grep -m1 "IPv4" | awk \'{print $NF}\' || echo "")\n' +
    '      ;;\n' +
    '  esac\n' +
    '  if [ -z "$ip" ]; then\n' +
    '    ip="127.0.0.1"\n' +
    '  fi\n' +
    '  echo "$ip"\n' +
    '}\n' +
    '\n' +
    'SYSTEM_IP=$(detect_ip)\n' +
    'REPO_DIR="$(cd "$(dirname "$0")" && pwd)"\n' +
    'REPO_NAME="$(basename "$REPO_DIR")"\n' +
    '\n' +
    'echo "System IP: $SYSTEM_IP"\n' +
    '\n' +
    '# ── Scan sibling repos for stack.yml ──────────────────────\n' +
    'PARENT_DIR="$(dirname "$REPO_DIR")"\n' +
    'SLOT=0\n' +
    'SLOT_NUM=0\n' +
    'echo "Scanning sibling repos..."\n' +
    'for dir in "$PARENT_DIR"/*/; do\n' +
    '  [ ! -d "$dir" ] && continue\n' +
    '  if [ -f "$dir/stack.yml" ] || [ -f "$dir/factiii.yml" ]; then\n' +
    '    SLOT_NUM=$((SLOT_NUM + 1))\n' +
    '    SIBLING_NAME="$(basename "$dir")"\n' +
    '    if [ "$SIBLING_NAME" = "$REPO_NAME" ]; then\n' +
    '      SLOT=$SLOT_NUM\n' +
    '      echo "  [$SLOT_NUM] $SIBLING_NAME  <-- this repo"\n' +
    '    else\n' +
    '      echo "  [$SLOT_NUM] $SIBLING_NAME"\n' +
    '    fi\n' +
    '  fi\n' +
    'done\n' +
    '\n' +
    'if [ "$SLOT_NUM" -eq 0 ]; then\n' +
    '  echo "  No sibling repos found with stack.yml"\n' +
    '  SLOT=1\n' +
    'fi\n' +
    '\n' +
    '# ── Determine PORT slot ───────────────────────────────────\n' +
    'if [ -f "$REPO_DIR/.env" ] && grep -q "^PORT=" "$REPO_DIR/.env"; then\n' +
    '  EXISTING_PORT=$(grep "^PORT=" "$REPO_DIR/.env" | cut -d= -f2)\n' +
    '  if [ "$EXISTING_PORT" -ge 1 ] && [ "$EXISTING_PORT" -le 9 ] 2>/dev/null; then\n' +
    '    SLOT=$EXISTING_PORT\n' +
    '    echo "Using existing PORT slot: $SLOT"\n' +
    '  fi\n' +
    'fi\n' +
    '\n' +
    'if [ "$SLOT" -eq 0 ]; then\n' +
    '  echo "Select PORT slot for $REPO_NAME:"\n' +
    '  echo "  Slot N -> client:300N, server:500N"\n' +
    '  read -p "  Enter slot number (1-5): " SLOT\n' +
    '  if ! [ "$SLOT" -ge 1 ] || ! [ "$SLOT" -le 5 ] 2>/dev/null; then\n' +
    '    echo "Invalid slot. Using 1."\n' +
    '    SLOT=1\n' +
    '  fi\n' +
    'fi\n' +
    '\n' +
    'CLIENT_PORT=$((3000 + SLOT))\n' +
    'SERVER_PORT=$((5000 + SLOT))\n' +
    'echo "Slot $SLOT -> Client: $CLIENT_PORT, Server: $SERVER_PORT"\n' +
    '\n' +
    '# ── Setup .env with IP + PORT ─────────────────────────────\n' +
    'if [ ! -f "$REPO_DIR/.env" ]; then\n' +
    '  if [ -f "$REPO_DIR/.env.example" ]; then\n' +
    '    cp "$REPO_DIR/.env.example" "$REPO_DIR/.env"\n' +
    '    echo "Copied .env.example -> .env"\n' +
    '  fi\n' +
    'fi\n' +
    '\n' +
    'if [ -f "$REPO_DIR/.env" ]; then\n' +
    '  # Inject PORT slot\n' +
    '  if grep -q "^PORT=" "$REPO_DIR/.env"; then\n' +
    '    sed -i.bak "s/^PORT=.*/PORT=$SLOT/" "$REPO_DIR/.env" && rm -f "$REPO_DIR/.env.bak"\n' +
    '  else\n' +
    '    echo "PORT=$SLOT" >> "$REPO_DIR/.env"\n' +
    '  fi\n' +
    '\n' +
    '  # Replace localhost/127.0.0.1 with system IP\n' +
    '  if [ "$SYSTEM_IP" != "127.0.0.1" ]; then\n' +
    '    sed -i.bak \\\n' +
    '      -e "s|http://localhost|http://$SYSTEM_IP|g" \\\n' +
    '      -e "s|http://127\\.0\\.0\\.1|http://$SYSTEM_IP|g" \\\n' +
    '      -e "s|YOUR_IP|$SYSTEM_IP|g" \\\n' +
    '      "$REPO_DIR/.env" && rm -f "$REPO_DIR/.env.bak"\n' +
    '    echo "Injected IP: $SYSTEM_IP"\n' +
    '  fi\n' +
    '\n' +
    '  # Update port references in URL values\n' +
    '  sed -i.bak \\\n' +
    '    -e "s|:500[0-9]|:${SERVER_PORT}|g" \\\n' +
    '    -e "s|:300[0-9]|:${CLIENT_PORT}|g" \\\n' +
    '    "$REPO_DIR/.env" && rm -f "$REPO_DIR/.env.bak"\n' +
    '\n' +
    '  echo "PORT=$SLOT (client:$CLIENT_PORT, server:$SERVER_PORT)"\n' +
    'fi\n' +
    '\n' +
    '# Export for use by the rest of start.sh\n' +
    'export SYSTEM_IP SLOT CLIENT_PORT SERVER_PORT\n' +
    MARKER_END + '\n';
}

/**
 * Generate a full start.sh for repos that don't have one
 */
function generateFullStartSh(rootDir: string): string {
  let composeFile = 'docker-compose.yml';
  if (fs.existsSync(path.join(rootDir, 'compose.yml'))) {
    composeFile = 'compose.yml';
  }

  return '#!/usr/bin/env bash\n' +
    'set -e\n' +
    '\n' +
    generateSlotSection() +
    '\n' +
    '# ── Install dependencies ────────────────────────────────────\n' +
    'echo "Installing dependencies..."\n' +
    'if command -v pnpm &>/dev/null; then\n' +
    '  cd "$REPO_DIR" && pnpm install\n' +
    'elif command -v npm &>/dev/null; then\n' +
    '  cd "$REPO_DIR" && npm install\n' +
    'fi\n' +
    '\n' +
    '# ── Start Docker ────────────────────────────────────────────\n' +
    'echo "Starting Docker..."\n' +
    'if command -v docker &>/dev/null; then\n' +
    '  cd "$REPO_DIR" && docker compose -f ' + composeFile + ' up -d\n' +
    'fi\n' +
    '\n' +
    '# ── init.sql detection ──────────────────────────────────────\n' +
    'if [ -f "$REPO_DIR/init.sql" ]; then\n' +
    '  echo ""\n' +
    '  echo "init.sql detected. How to set up the database?"\n' +
    '  echo "  1) Inject init.sql into the database container"\n' +
    '  echo "  2) Use the seed script (pnpm prisma db seed / pnpm seed)"\n' +
    '  echo "  3) Skip"\n' +
    '  read -p "  Choose (1/2/3): " DB_CHOICE\n' +
    '\n' +
    '  case "$DB_CHOICE" in\n' +
    '    1)\n' +
    '      DB_CONTAINER=$(docker compose -f "$REPO_DIR/' + composeFile + '" ps --format "{{.Name}}" 2>/dev/null | grep -iE "db|postgres|mysql" | head -1 || echo "")\n' +
    '      [ -z "$DB_CONTAINER" ] && read -p "  DB container name: " DB_CONTAINER\n' +
    '      if [ -n "$DB_CONTAINER" ]; then\n' +
    '        sleep 3\n' +
    '        if docker exec "$DB_CONTAINER" psql --version &>/dev/null; then\n' +
    '          DB_USER=$(grep "POSTGRES_USER" "$REPO_DIR/.env" 2>/dev/null | cut -d= -f2 || echo "postgres")\n' +
    '          DB_NAME=$(grep "POSTGRES_DB" "$REPO_DIR/.env" 2>/dev/null | cut -d= -f2 || echo "postgres")\n' +
    '          docker exec -i "$DB_CONTAINER" psql -U "${DB_USER:-postgres}" -d "${DB_NAME:-postgres}" < "$REPO_DIR/init.sql"\n' +
    '          echo "init.sql injected into PostgreSQL"\n' +
    '        elif docker exec "$DB_CONTAINER" mysql --version &>/dev/null; then\n' +
    '          DB_NAME=$(grep "MYSQL_DATABASE" "$REPO_DIR/.env" 2>/dev/null | cut -d= -f2 || echo "app")\n' +
    '          docker exec -i "$DB_CONTAINER" mysql -u root "${DB_NAME:-app}" < "$REPO_DIR/init.sql"\n' +
    '          echo "init.sql injected into MySQL"\n' +
    '        fi\n' +
    '      fi\n' +
    '      ;;\n' +
    '    2)\n' +
    '      cd "$REPO_DIR"\n' +
    '      if [ -f "prisma/schema.prisma" ]; then\n' +
    '        pnpm prisma db seed 2>/dev/null || npx prisma db seed 2>/dev/null || echo "Seed failed"\n' +
    '      elif grep -q "\\"seed\\"" package.json 2>/dev/null; then\n' +
    '        pnpm seed 2>/dev/null || npm run seed 2>/dev/null || echo "Seed failed"\n' +
    '      fi\n' +
    '      ;;\n' +
    '    *) echo "Skipping database setup" ;;\n' +
    '  esac\n' +
    'fi\n' +
    '\n' +
    'echo ""\n' +
    'echo "Ready! Client: http://$SYSTEM_IP:$CLIENT_PORT  Server: http://$SYSTEM_IP:$SERVER_PORT"\n';
}

/**
 * Inject or update the slot section in an existing start.sh
 */
function mergeSlotSection(existingContent: string): string {
  const slotSection = generateSlotSection();

  // If markers already exist, replace the section between them
  if (existingContent.includes(MARKER_BEGIN) && existingContent.includes(MARKER_END)) {
    const beforeMarker = existingContent.substring(0, existingContent.indexOf(MARKER_BEGIN));
    const afterMarker = existingContent.substring(
      existingContent.indexOf(MARKER_END) + MARKER_END.length
    );
    // Strip leading newline from afterMarker to avoid double blank lines
    const trimmedAfter = afterMarker.startsWith('\n') ? afterMarker.substring(1) : afterMarker;
    return beforeMarker + slotSection + trimmedAfter;
  }

  // No markers yet — inject after shebang + set -e block
  const lines = existingContent.split('\n');
  let insertIndex = 0;

  // Find the right spot: after shebang, comments, set -e, blank lines
  for (let i = 0; i < lines.length; i++) {
    const trimmed = lines[i]!.trim();
    if (trimmed.startsWith('#!') || trimmed.startsWith('#') || trimmed === '' || trimmed === 'set -e') {
      insertIndex = i + 1;
    } else {
      break;
    }
  }

  const before = lines.slice(0, insertIndex).join('\n');
  const after = lines.slice(insertIndex).join('\n');

  return before + '\n\n' + slotSection + '\n' + after;
}

export const startShFixes: Fix[] = [
  {
    id: 'missing-start-sh',
    stage: 'dev',
    severity: 'warning',
    description: '🚀 start.sh missing slot setup (IP detection + PORT slot injection)',
    scan: async (_config: FactiiiConfig, rootDir: string): Promise<boolean> => {
      if (!hasEnvironments(_config)) return false;
      const hasCompose =
        fs.existsSync(path.join(rootDir, 'docker-compose.yml')) ||
        fs.existsSync(path.join(rootDir, 'compose.yml'));
      if (!hasCompose) return false;

      const startPath = path.join(rootDir, 'start.sh');
      if (!fs.existsSync(startPath)) return true;

      // Check if slot section exists and is current version
      const content = fs.readFileSync(startPath, 'utf8');
      if (!content.includes(MARKER_BEGIN)) return true;

      // Check version
      const version = getFactiiiVersion();
      return !content.includes('Generated by @factiii/stack v' + version);
    },
    fix: async (_config: FactiiiConfig, rootDir: string): Promise<boolean> => {
      const startPath = path.join(rootDir, 'start.sh');

      if (fs.existsSync(startPath)) {
        // Existing start.sh — merge slot section into it
        const existing = fs.readFileSync(startPath, 'utf8');
        const merged = mergeSlotSection(existing);
        fs.writeFileSync(startPath, merged, 'utf8');
        console.log('   Merged slot setup into existing start.sh');
      } else {
        // No start.sh — generate full version
        const content = generateFullStartSh(rootDir);
        fs.writeFileSync(startPath, content, 'utf8');
        console.log('   Created start.sh (slot-based quick-start)');
      }

      try {
        fs.chmodSync(startPath, 0o755);
      } catch {
        // Windows doesn't support chmod
      }
      return true;
    },
    manualFix:
      'Run: npx stack fix (will inject slot setup into start.sh)\n' +
      '      Or manually add IP detection + PORT slot system to start.sh',
  },
];
