/**
 * Workflow-related fixes for Factiii Pipeline plugin
 * Handles GitHub workflow generation, validation, and cleanup
 */

import * as fs from 'fs';
import * as path from 'path';
import { execSync } from 'child_process';
import type { FactiiiConfig, Fix } from '../../../../types/index.js';
import { generateWorkflows as generateWorkflowsUtil } from '../utils/workflows.js';

export const workflowFixes: Fix[] = [
  {
    id: 'missing-workflows',
    stage: 'dev',
    severity: 'warning',
    description: 'GitHub workflows not generated',
    scan: async (_config: FactiiiConfig, rootDir: string): Promise<boolean> => {
      const workflowsDir = path.join(rootDir, '.github', 'workflows');
      return !fs.existsSync(path.join(workflowsDir, 'factiii-deploy.yml'));
    },
    fix: async (_config: FactiiiConfig, rootDir: string): Promise<boolean> => {
      await generateWorkflowsUtil(rootDir);
      return true;
    },
    manualFix: 'Run: npx factiii fix (will generate workflow files)',
  },
  {
    id: 'outdated-workflows',
    stage: 'dev',
    severity: 'info',
    description: 'GitHub workflows may be outdated',
    scan: async (_config: FactiiiConfig, rootDir: string): Promise<boolean> => {
      const workflowPath = path.join(
        rootDir,
        '.github',
        'workflows',
        'factiii-deploy.yml'
      );
      if (!fs.existsSync(workflowPath)) return false;

      const content = fs.readFileSync(workflowPath, 'utf8');

      // Check if using old bloated workflow (has inline bash logic not from template)
      if (content.includes('docker compose build')) return true;

      // Check version comment
      const packageJsonPath = path.join(__dirname, '../../../../../package.json');
      const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, 'utf8'));
      const currentVersion = packageJson.version;

      const versionMatch = content.match(/# Generated by @factiii\/stack v([\d.]+)/);
      if (!versionMatch) return true; // No version comment = outdated

      const workflowVersion = versionMatch[1];
      return workflowVersion !== currentVersion;
    },
    fix: async (_config: FactiiiConfig, rootDir: string): Promise<boolean> => {
      await generateWorkflowsUtil(rootDir);
      return true;
    },
    manualFix: 'Run: npx factiii fix (will regenerate thin workflows)',
  },
  {
    id: 'orphaned-workflows',
    stage: 'dev',
    severity: 'warning',
    description: 'Old workflow files found that are not generated by current version',
    scan: async (_config: FactiiiConfig, rootDir: string): Promise<boolean> => {
      const workflowsDir = path.join(rootDir, '.github', 'workflows');
      if (!fs.existsSync(workflowsDir)) return false;

      // List of workflows we currently generate
      const validWorkflows = [
        'factiii-deploy.yml',
        'factiii-fix.yml',
        'factiii-scan.yml',
        'factiii-undeploy.yml',
        'factiii-cicd-staging.yml',
        'factiii-cicd-prod.yml',
        'factiii-dev-sync.yml', // Only in dev mode
      ];

      // Find all factiii-*.yml files
      const files = fs.readdirSync(workflowsDir);
      const factiiiFiles = files.filter((f) => f.startsWith('factiii-') && f.endsWith('.yml'));

      // Check for orphaned files
      const orphaned = factiiiFiles.filter((f) => !validWorkflows.includes(f));

      return orphaned.length > 0;
    },
    fix: async (_config: FactiiiConfig, rootDir: string): Promise<boolean> => {
      const workflowsDir = path.join(rootDir, '.github', 'workflows');

      const validWorkflows = [
        'factiii-deploy.yml',
        'factiii-fix.yml',
        'factiii-scan.yml',
        'factiii-undeploy.yml',
        'factiii-cicd-staging.yml',
        'factiii-cicd-prod.yml',
        'factiii-dev-sync.yml',
      ];

      const files = fs.readdirSync(workflowsDir);
      const factiiiFiles = files.filter((f) => f.startsWith('factiii-') && f.endsWith('.yml'));
      const orphaned = factiiiFiles.filter((f) => !validWorkflows.includes(f));

      for (const file of orphaned) {
        const filePath = path.join(workflowsDir, file);
        fs.unlinkSync(filePath);
        console.log(`   🗑️  Deleted orphaned workflow: ${file}`);
      }

      return orphaned.length > 0;
    },
    manualFix: 'Run: npx factiii fix (will remove old workflow files)',
  },
  {
    id: 'workflows-uncommitted',
    stage: 'dev',
    severity: 'critical',
    description: 'GitHub workflows not committed to git',
    scan: async (_config: FactiiiConfig, rootDir: string): Promise<boolean> => {
      const workflowsDir = path.join(rootDir, '.github', 'workflows');
      if (!fs.existsSync(workflowsDir)) return false;

      try {
        // Check git status for workflow files
        const status = execSync('git status --porcelain .github/workflows/', {
          cwd: rootDir,
          encoding: 'utf8',
          stdio: ['pipe', 'pipe', 'ignore'],
        });

        // If there's any output, workflows are uncommitted or untracked
        return status.trim().length > 0;
      } catch {
        // Not a git repo or git not available
        return false;
      }
    },
    fix: null, // Cannot auto-commit
    manualFix:
      'Commit and push workflows: git add .github/workflows/ && git commit -m "Update workflows" && git push',
  },
];

