/**
 * Generate docker-compose.yml for a single-tenant prod VM.
 *
 * Runs on the dev machine. Output is uploaded to the prod server via SSH —
 * prod never runs this code and never needs Node or the stack CLI.
 *
 * Matches the shape that `aws/prod.ts` used to construct inline: postgres +
 * app + nginx, single factiii network, nginx-owned ports 80/443. Keeping the
 * shape identical preserves upgrade-in-place behavior for servers that
 * already have the old file on disk.
 */

import yaml from 'js-yaml';

import type { FactiiiConfig, EnvironmentConfig } from '../types/index.js';

export interface GenerateProdComposeOptions {
  stage: string;
  imageTag: string;
  envConfig: EnvironmentConfig;
  stackVersion?: string;
}

export function generateProdCompose(
  config: FactiiiConfig,
  opts: GenerateProdComposeOptions,
): string {
  const rawName = config.name ?? 'app';
  const repoName = rawName.replace(/[^a-zA-Z0-9_-]/g, '');
  const serviceName = repoName + '-' + opts.stage;
  const dbName = repoName.replace(/[^a-zA-Z0-9]/g, '') + '-' + opts.stage;
  const envFile = './' + repoName + '/.env.' + opts.stage;

  const composeObj: Record<string, unknown> = {
    version: '3.8',
    services: {
      postgres: {
        image: 'postgres:15-alpine',
        container_name: 'factiii_postgres',
        restart: 'unless-stopped',
        environment: [
          'POSTGRES_USER=postgres',
          'POSTGRES_PASSWORD=postgres',
          'POSTGRES_DB=' + dbName,
        ],
        volumes: ['postgres_data:/var/lib/postgresql/data'],
        expose: ['5432'],
        networks: ['factiii'],
        healthcheck: {
          test: ['CMD-SHELL', 'pg_isready -U postgres -d ' + dbName],
          interval: '10s',
          timeout: '5s',
          retries: 5,
        },
      },
      [serviceName]: {
        image: opts.imageTag,
        container_name: serviceName,
        restart: 'unless-stopped',
        networks: ['factiii'],
        expose: ['3000'],
        env_file: [envFile],
        environment: {
          DATABASE_URL:
            'postgresql://postgres:postgres@postgres:5432/' + dbName + '?connect_timeout=300',
        },
        depends_on: {
          postgres: { condition: 'service_healthy' },
        },
      },
      nginx: {
        image: 'nginx:alpine',
        container_name: 'factiii_nginx',
        ports: ['80:80', '443:443'],
        volumes: [
          './nginx.conf:/etc/nginx/nginx.conf:ro',
          '/etc/letsencrypt:/etc/letsencrypt:ro',
          '/var/www/certbot:/var/www/certbot:ro',
        ],
        networks: ['factiii'],
        restart: 'unless-stopped',
        depends_on: [serviceName],
      },
    },
    volumes: {
      postgres_data: {},
    },
    networks: {
      factiii: { driver: 'bridge' },
    },
  };

  const banner = opts.stackVersion
    ? '# Generated by @factiii/stack v' + opts.stackVersion + '\n'
    : '# Generated by @factiii/stack\n';

  return banner + yaml.dump(composeObj, { lineWidth: -1 });
}

/**
 * Compute the service name used for the app container in the generated compose.
 * Exposed so callers can reference it when issuing `docker compose pull/up` via SSH.
 */
export function prodComposeServiceName(config: FactiiiConfig, stage: string): string {
  const repoName = config.name ?? 'app';
  return repoName + '-' + stage;
}
