/**
 * Generate nginx.conf for a single-tenant prod VM.
 *
 * Runs on the dev machine; output is uploaded to prod via SSH. Matches the
 * HTTP-only shape the inline generator used — certbot rewrites the server
 * block afterwards to add HTTPS when a cert is obtained.
 */

import type { FactiiiConfig } from '../types/index.js';

export interface GenerateProdNginxOptions {
  stage: string;
  domain: string;
  stackVersion?: string;
}

export function generateProdNginx(
  config: FactiiiConfig,
  opts: GenerateProdNginxOptions,
): string {
  const repoName = config.name ?? 'app';
  const serviceName = repoName + '-' + opts.stage;
  const banner = opts.stackVersion
    ? '# Generated by @factiii/stack v' + opts.stackVersion
    : '# Generated by @factiii/stack';

  return [
    banner,
    'events { worker_connections 1024; }',
    'http {',
    '    include /etc/nginx/mime.types;',
    '    default_type application/octet-stream;',
    '    sendfile on;',
    '    keepalive_timeout 65;',
    '    client_max_body_size 100M;',
    '    gzip on;',
    '    gzip_vary on;',
    '    gzip_types text/plain text/css application/json application/javascript text/xml;',
    '',
    '    server {',
    '        listen 80;',
    '        server_name ' + opts.domain + ';',
    '',
    '        location /.well-known/acme-challenge/ {',
    '            root /var/www/certbot;',
    '        }',
    '',
    '        location / {',
    '            proxy_pass http://' + serviceName + ':3000;',
    '            proxy_http_version 1.1;',
    '            proxy_set_header Upgrade $http_upgrade;',
    '            proxy_set_header Connection "upgrade";',
    '            proxy_set_header Host $host;',
    '            proxy_set_header X-Real-IP $remote_addr;',
    '            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;',
    '            proxy_set_header X-Forwarded-Proto $scheme;',
    '        }',
    '    }',
    '}',
  ].join('\n');
}
